homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://172.17.0.1:1883  # docker0 bridge
serial:
  port: /dev/ttyACM0
frontend: true
devices:
  '0x0022a300003d42bd':
    friendly_name: FrontOutsideLights
