# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

autoload -U compinit
compinit

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

## keep background processes at full speed
#setopt NOBGNICE
## restart running processes on exit
#setopt HUP

## history
# https://linuxhandbook.com/zsh-command-history/
#HISTFILE=~/.zsh_history
setopt APPEND_HISTORY
# for sharing history between zsh processes
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
# How many commands to store in history
HISTSIZE=10000
SAVEHIST=10000
# Do not save duplicate commands to history
setopt HIST_IGNORE_ALL_DUPS
# Do not find duplicate command when searching
setopt HIST_FIND_NO_DUPS
# Clear history file
# truncate -s 0 "${HISTFILE}"

## never ever beep ever
#setopt NO_BEEP

## automatically decide when to page a list of completions
#LISTMAX=0

## disable mail checking
MAILCHECK=0

# autoload -U colors
#colors

# apk add zsh alpine-zsh-config zsh-theme-powerlevel10k
source /usr/share/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# apk add zsh-completions
# This project gathers new completion scripts that are not available in Zsh yet...
#source /usr/share/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
fpath=(/usr/share/zsh/plugins/zsh-completions/src $fpath)
# may have to force rebuild
# rm -f ~/.zcompdump; compinit

# apk add zsh-autosuggestions
# This looks through .history and adds grey text of previous commands as you are typing
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# apk add zsh-history-substring-search
# This looks through .zsh_history and narrows down which previous commands you have run
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
# Run "cat -v" and hit up and down arrows to verify key codes
# zsh-history-substring-search configuration
#   (run "cat -v" and hit up and down arrows to verify key codes)
bindkey '^[[A' history-substring-search-up # or '\eOA'
bindkey '^[[B' history-substring-search-down # or '\eOB'
HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1

# git clone https://github.com/zdharma-continuum/fast-syntax-highlighting
# This changes the colors of commands you type (green = found, red = not found, etc)
source ~/source/zdharma-continuum/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# git clone https://github.com/agkozak/zsh-z
# This keeps track of the directories you use / Use Tab to jump to recent or most used directories
source ~/source/agkozak/zsh-z/zsh-z.plugin.zsh
zstyle ':completion:*' menu select

# mkdir ~/source/MichaelAquilina; cd ~/source/MichaelAquilina; git clone --depth=1 https://github.com/MichaelAquilina/zsh-autoswitch-virtualenv
# This activates a .venv Python virtual environment if it exists / rmvenv && mkvenv
#source ~/source/MichaelAquilina/zsh-autoswitch-virtualenv/autoswitch_virtualenv.plugin.zsh
#export AUTOSWITCH_DEFAULTENV="~/.venv"

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

